# Generated by Django 5.1.1 on 2024-10-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sleep_habit', models.CharField(max_length=100)),
                ('sports_interest', models.CharField(max_length=100)),
                ('dietary_preference', models.CharField(max_length=100)),
            ],
        ),
    ]
